/**
 * `arcpayments add paywall` — scaffold a gated tool wired to {@link PaywallGuard}.
 * Pure core (render + decide-to-write); the CLI supplies real filesystem deps.
 */

/** Options for rendering a paywall-gated tool template. */
export interface RenderPaywallOptions {
  /** Tool name (also the export/identifier base). */
  name: string;
  /** Price string, e.g. "$0.001". */
  price: string;
}

/** Render a self-contained gated-tool scaffold as TypeScript source. */
export function renderPaywallTemplate(options: RenderPaywallOptions): string {
  const { name, price } = options;
  return `// Generated by \`arcpayments add paywall ${name}\`.
// A paid tool gated by the x402 paywall. Verify locally, then queue for batch
// settlement — never broadcast per call. Amounts use 6-decimal USDC (ERC-20).
import {
  buildPaymentRequirements,
  InMemoryNonceStore,
  InMemorySettlementQueue,
  LocalExactVerifier,
  loadNetworkConfig,
  PaywallGuard,
  USDC_ERC20_DECIMALS,
  type ExactPaymentPayload,
} from "arcpayments";

const PRICE = "${price}";

/** Build a guard for the "${name}" resource. Reads endpoints from env/NETWORK.md. */
export function create${toPascal(name)}Guard(payTo: \`0x\${string}\`) {
  const net = loadNetworkConfig();
  return new PaywallGuard({
    requirements: buildPaymentRequirements({
      price: PRICE,
      payTo,
      caip2: net.caip2,
      asset: net.usdcAddress,
      verifyingContract: net.gatewayWallet,
      usdcDecimals: USDC_ERC20_DECIMALS,
      eip712: net.x402Domain,
      maxTimeoutSeconds: net.x402MinValiditySeconds,
    }),
    verifier: new LocalExactVerifier(new InMemoryNonceStore()),
    queue: new InMemorySettlementQueue(),
  });
}

/** Run "${name}" behind the paywall. Returns the challenge, a rejection, or the result. */
export async function ${toCamel(name)}(
  guard: ReturnType<typeof create${toPascal(name)}Guard>,
  input: { payment?: ExactPaymentPayload },
) {
  return guard.guard(input.payment, async () => {
    // TODO: implement the paid work for "${name}".
    return { ok: true };
  });
}
`;
}

function toPascal(name: string): string {
  return name
    .split(/[^a-zA-Z0-9]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

function toCamel(name: string): string {
  const pascal = toPascal(name);
  return pascal.charAt(0).toLowerCase() + pascal.slice(1);
}

/** Injectable filesystem deps for {@link runAddPaywall} (keeps the core testable). */
export interface AddPaywallDeps {
  name: string;
  price: string;
  outPath: string;
  force: boolean;
  fileExists: (path: string) => boolean;
  writeFile: (path: string, contents: string) => void;
}

export interface AddPaywallResult {
  ok: boolean;
  error?: string;
  outPath: string;
}

/** Write the scaffold, refusing to overwrite an existing file without `force`. */
export function runAddPaywall(deps: AddPaywallDeps): AddPaywallResult {
  if (deps.fileExists(deps.outPath) && !deps.force) {
    return {
      ok: false,
      error: `${deps.outPath} already exists — pass --force to overwrite.`,
      outPath: deps.outPath,
    };
  }
  deps.writeFile(deps.outPath, renderPaywallTemplate({ name: deps.name, price: deps.price }));
  return { ok: true, outPath: deps.outPath };
}
